[package]
name = "calibration_web_app"
version = "0.1.0"
authors = ["serejkaaa512"]

[dependencies]
nickel = "*"
url = "*"
groupable = "*"
typemap="*"
plugin="*"
rustc-serialize = "*"
time="*"
regex="*"

[dependencies.mysql]
mysql = "*"
default-features = false
features = ["pipe"]
